import { DocumentKindValue, type DocumentKind } from '@apptly/shared';

// Users upload their own CV/resume (required) and, optionally, a cover letter.
// Tailored CVs are generated by Apptly, not uploaded, so they're not an option.
export const DOCUMENT_KIND_OPTIONS: { value: DocumentKind; label: string }[] = [
  { value: DocumentKindValue.Resume, label: 'Resume / CV' },
  { value: DocumentKindValue.CoverLetter, label: 'Cover letter' },
];

export const DOCUMENT_UPLOAD_COPY = {
  document: 'Document',
  kind: 'Kind',
  chooseFile: 'Choose a PDF or DOCX file.',
  upload: 'Upload',
  uploading: 'Uploading...',
  uploaded: 'Document uploaded',
  hint: 'A CV/resume is required (PDF or DOCX). A cover letter is optional.',
};
